# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet_tf',
            name='packet_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
