# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_packet_tf_raw_load'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packet_tf',
            old_name='TCP_flags_TCP',
            new_name='TCP_flags',
        ),
    ]
