# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20160609_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet_tf',
            name='IP_flags',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='IP_frag',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='IP_ihl',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='IP_version',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='TCP_dataofs',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='TCP_flags',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='packet_tf',
            name='TCP_reserved',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
