# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_auto_20160619_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet_tf',
            name='Raw_load',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
